### ISSUE TITLE
Blocks standard browser contextmenu/wheel event

### ISSUE THREAD

**Issue by Drumstix42** [Koorosh/dom-events#1]
Using this plugin has great benefits, but by default it blocks the scroll event and context menu on the charts. This is an issue with large charts, preventing the user from using the scroll mouse on the page.

Preferably **stopPropagation()**, **preventDefault()**, and **return false;** for events would only happen if an actual event is defined, or allow the custom event to call this.

I attempted to modify the code, but since it calls contextmenu on both the series and the point, it seems you actually have to create extra events just to **preventDefault()** etc.

**Comment by Drumstix42** [comment]
Looks like you can just remove these lines from the container.oncontextmenu/container.onwheel statements
`            e.stopPropagation();`
`            e.preventDefault();`

And then use `return false;` in the highcharts event, to achieve this. I was mislead by highcharts default functionality where a linechart "point" event will still trigger when clicking on the series. I'll need to figure that part out separately...

**Comment by koorosh** [comment]
Fixed with commit [Allow bubbling events](https://github.com/Koorosh/dom-events/commit/4ee5d72983c2473874bec0259a79d4e3ba315fd6l)
